content/markdown/maven-logging.md

Simply adding `-Dorg.slf4j.simpleLogger.showThreadName=true` to the command line doesn't work as implied, so I tried to expand the explanation a bit.
Feel free to edit in a better URL for `simplelogger.properties` (eg something on apache.org).

Mention MAVEN_OPTS for SLF4J config; fix URL

---

content/apt/guides/introduction/introduction-to-dependency-mechanism.apt

We probably shouldn't clutter the docs with special cases for versions no one uses any more.

Maven 2.0.8 is over 10 years old.

---

content/markdown/code-quality-management.md

an "i" was missing in the CMD and Checkstyle maven plugin links

Fixed 2 links

---

content/xdoc/articles.xml

Some old links are broken, we could use archive.org to still be able to see the content of the articles.

Fix broken links using archive.org

---

content/apt/guides/mini/guide-configuring-maven.apt

Clicking "Guide to Password Encryption." currently incorrectly takes you to "https://maven.apache.org/guides/mini/guides/mini/guide-encryption.html".  I believe it intends to take you to "https://maven.apache.org/guides/mini/guide-encryption.html".   This commit should resolve this, but requires testing.

Broken link to password encryption guide

---

content/markdown/maven-ci-friendly.md

The flatten-maven-plugin configuration shown in the example [maven-ci-friendly.md ## Install / Deploy](https://maven.apache.org/maven-ci-friendly.html#Install_.2F_Deploy) may lead to unusable pom for consumers. The configuration should use the following mode `<flattenMode>resolveCiFriendliesOnly</flattenMode>` by default.
At this time this `resolveCiFriendliesOnly` mode do not however appear in the [official doc](https://www.mojohaus.org/flatten-maven-plugin/flatten-mojo.html#flattenMode) of the plugin (issue https://github.com/mojohaus/flatten-maven-plugin/issues/84), but can be found in the [FlattenMode source code](https://github.com/mojohaus/flatten-maven-plugin/blob/flatten-maven-plugin-1.1.0/src/main/java/org/codehaus/mojo/flatten/FlattenMode.java#L77-L80)

Fixes default flatten configuration in Install / Deploy in CI friendly documentation

---

content/apt/guides/introduction/introduction-to-repositories.apt

1. CVS is very rarely used any more
2. Nothing said here is the primary reason. Generated artifacts don't belong in source repos for much more important reasons. 
3. In 2018 devs are much less likely to try this. Maven repos are the default assumption. 
If you don't agree the entire section can simply be deleted, I can try to write an alternate reason why jars don't belong in source control.

remove section on CVS

---

content/apt/guides/introduction/introduction-to-dependency-mechanism.apt

@hboutemy FYI, I'm tempted to delete this note completely since it describes a situation that doesn't happen (compile+compile --> runtime), and I'm not sure a typical user of Maven needs to think about this. They just need to know what Maven does do, not what we sort of wish it could do.

Add missing word and tighten

---

content/apt/guides/mini/guide-relocation.apt

Hi,
Trying to relocate a repository, so am reading this page in Maven site, and found a typo.
Thanks for the documentation!
Bruno

Fix typo in relocation mini-guide

---

content/apt/guides/development/guide-maven-development.apt

It refers to SVN and submitting patches through JIRA, which is not the current approach.
Instead, the guide now refers to submitting GitHub pull requests.

[MNGSITE-371] Update "Guide to Developing Maven"

---

content/apt/guides/development/guide-maven-development.apt

The current text could be interpreted in such a way that the branch should always start with `MNG-`. This is - of course - not the case. The new text is a bit more clear about that.

[MNGSITE-371] Clarify that the issue number is an example

---

content/apt/guides/mini/guide-creating-archetypes.apt

Using the pom in creating archetype guide results in the following error:
```
[ERROR]     Unknown packaging: maven-archetype @ line 9, column 16
```
I was able to resolve this by adding `archetype-packaging` extension.
Suggesting this change to the page to supply users with a working version of the example archetype pom.
Please correct me if there is a different way to handle this error, I found no other way.

Adding extension to support packaging type maven-archetype in creating archetypes guide

---

content/markdown/repository-management.md

Hi team!
Appreciate your best practices article here - helpful high-level introduction article to provide context!
Proposing to include https://www.myget.org to the list of repository managers that support Maven in the list at the bottom of the article, for the sake of completeness/accuracy!

Add MyGet to list Maven repository managers

---

content/markdown/docs/3.6.2/release-notes.md

This PR is still work in progress.
It contains the release notes for Apache Maven Core release 3.6.2

Release notes for Apache Maven 3.6.2

---

content/apt/pom.apt

Expand on hard and soft requirements

---

content/markdown/ide.md

NetBeans is no longer owned by Oracle and is now an Apache Project.  I have updated the name of of the IDE accordingly.
We haven't migrated the link to our new infrastructure yet so will need to update it later but this link still provides the correct information.

Updating Reference to NetBeans to Apache NetBeans

---

content/apt/pom.apt

Using SPDX identifiers as license names makes it much easier to unambiguously identify the used license, in particular by tools like the [Mojohaus License Maven Plugin](https://www.mojohaus.org/license-maven-plugin/) (e. g. because the configuration will be much shorter when only SPDX identifiers are used).

Using an SPDX identifier as the license name is recommended.

---

content/apt/guides/mini/guide-multiple-modules.apt

While working on [MNG-4660](https://issues.apache.org/jira/browse/MNG-4660), I noticed that the wording in the "Guide to Working with Multiple Modules" was a bit unclear. Here's a suggestion how to fix that.

[MNG-4660] Improve documentation

---

content/apt/guides/introduction/introduction-to-optional-and-excludes-dependencies.apt

Currently the link is constructed this way
```
[banned dependencies rule](https://maven.apache.org/enforcer/enforcer-rules/bannedDependencies.html)
```
But even though that's valid Markdown syntax, the file is an APT (Almost Plain Text) instead of MD.
The correct syntax should be
```
{{{https://maven.apache.org/enforcer/enforcer-rules/bannedDependencies.html}banned dependencies rule}}
```

MNGSITE-399 - Fix the `banned dependencies rule` link at `Optional Dependencies and Dependency Exclusions` 

---

content/apt/guides/mini/guide-encryption.apt

@eolivelli and generally tighten language

[MNGSITE-393] Remove pre-Maven 3 comments

---

content/apt/pom.apt

Change the word "plugins" to "artifacts" when referring to the majority of artifacts in the central repository.

Change 'plugins' to 'artifacts' in pom.apt

---

content/xdoc/articles.xml

Add a reference to my own blog post 'Customise the Maven Release process'. The reason I'm creating a merge request is two-fold:
1. I'm not sure if this place on the site is the right place for this kind of content.
1. I'm also the author of the blog post so I'd appreciate if somebody else could confirm it's a useful resource to list on the Maven website.

Add 'Customise the Maven Release process' blog

---

content/apt/guides/introduction/introduction-to-profiles.apt

Previously the list was incomplete but did not infer the list was partial, e.g.
by using the word "some". If a user comes across the introductory guide first,
then it is easy to miss the complete model documentation and not find the
complete set of valid elements.
As discussed, the following have been updated:
- the remaining few elements have been added to complete the list.
- a link to the full model documentation is now provided.

document all allowed elements inside profiles

---

content/markdown/maven-ci-friendly.md

Looks like this was the only line using tabs for indentation.
See also: https://maven.apache.org/maven-ci-friendly.html#dependencies

Fix indentation

---

content/apt/guides/mini/guide-reproducible-builds.apt

Since [MEAR-280](https://issues.apache.org/jira/browse/MEAR-280) and [MEAR-283](https://issues.apache.org/jira/browse/MEAR-283), the maven-ear-plugin supports reproducible builds. So, the minimum version is 3.1.0.

The maven-ear-plugin supports reproducible builds since 3.1.0

---

content/apt/guides/introduction/introduction-to-profiles.apt

With the introduction of "?" as an optionality indicator, the example for profile deactivation became slightly overloaded. To really demonstrate use of '-' (which is happily not interpreted by the shell, hence not requiring escaping), introduce a separate example.

[MNGSITE-449] Clarify usage of '-' for profile deactivation

---

content/apt/guides/mini/guide-mirror-settings.apt

@hboutemy and a few other minor fixes

[MNGSITE-393] remove references to Maven 2

---

content/apt/guides/mini/guide-using-toolchains.apt

UTF8 is an illegal name of the UTF-8 encoding. The dash is mandatory.

Fix encoding in the example of toolchains.xml

---

content/apt/guides/mini/guide-site.apt

Just a one-character fix, but it was enough to confuse me for a bit. :sweat_smile:
Since there's already a `site-deploy` phase in the built-in `site` lifecycle, I thought perhaps there was also a `site-stage` phase, and went looking around for it to understand why it wasn't mentioned in the list of phases of the site lifecycle (and of course I didn't find it.)

guide-site.apt: fix typo in mvn command

---

content/apt/guides/introduction/introduction-to-the-lifecycle.apt

This allows them to be individually linked to, is better semantic markup to indicate the structure of the content, and is more consistent with the other divisions in this page.

Lifecycle intro: change bold into section headings

---

content/markdown/extensions/index.md

This PR adds the [Gradle Enterprise Maven extension](https://docs.gradle.com/enterprise/maven-extension/) to the list of "Outside The Maven Land" extensions. I interpreted the existing data as being sorted alphabetically and hence added it at the top of the list. Please let me know if you want a different order or any other changes.
---

Add Gradle Enterprise extension

---

content/markdown/run.md

"package" could be misunderstood by a newcomer to be a placeholder for the name of a package.
Using "compile" instead reduces the chances of ambiguity.
I've also added a commit fixing a duplicated word.

run.md: change example to use the "compile" phase

---

README.md
content/fml/about.fml
content/markdown/community.md
content/xdoc/index.xml.vm

FreeNode's #maven is not active anymore. Replaced with some Slack information is more pointing to the right communication channel.

[MNGSITE-461] Remove IRC contact channel from documentation

---

content/apt/pom.apt

In a POM, one would often like to restrict a dependency to a version before the next major release (incl. pre-releases). This does not work as most people would expect. So the proposed paragraph explains how to do it.

Version requirement for versions before next major release

---

content/xdoc/articles.xml

Add a reference to the blog post 'What's New in Maven 4' by @MartinKanters and myself. The reason I'm creating a merge request is two-fold:
1. I'm not sure if this place on the site is the right place for this kind of content.
1. I'm also the co-author of the blog post so I'd appreciate if somebody else could confirm it's a useful resource to list on the Maven website.

Add 'What's New in Maven 4' blog

---

content/apt/guides/introduction/introduction-to-profiles.apt

Changed "it's" to "its" in the documentation about Maven profiles.

Minor fix: grammar

---

content/markdown/what-is-maven.md

The word "Maven" was missing in this sentence:
> While takes an opinionated approach to project layout, some projects may not fit with this structure for historical reasons.
Should be "While Maven takes" rather than "While takes". Nice and simple fix!

docs: add missing word on What Is Maven page

---

content/apt/guides/mini/guide-mirror-settings.apt

I'm also planning to update https://repo.maven.apache.org/maven2/.meta/repository-metadata.xml with a list of current mirrors (outdated mirrors have been commented out and Google mirrors added).

Removing line about contacting Sonatype to set up a new mirror

---

content/markdown/extensions/index.md

Adds the predictive test selection feature to the description of the Gradle Enterprise Maven extension. This enhances the changes in this pull request: https://github.com/apache/maven-site/pull/258
Second commit formats the file.

Add predictive test selection to Gradle Enterprise Maven extension

---

content/apt/guides/mini/guide-configuring-plugins.apt

There is no converters from String to Map, Properties So we can not use property for parameter of this type
Tested with Maven 3.8.6 and I have:
```
Cannot assign configuration entry 'properties' with value '${myProp}' of type java.lang.String to property of type java.util.Properties 
```
```
Cannot assign configuration entry 'myMap' with value '${myMap}' of type java.lang.String to property of type java.util.Map
```

Remove property from parameter for Map and Properties

---

content/apt/guides/mini/guide-configuring-plugins.apt

Document missing string -> map and string -> properties coercion

Document limitation of comma-separated collections/arrays

---

content/fml/project-faq.fml

@michael-o IBiblio hasn't been Maven central for years, and I don't think anyone at Apache is actively curating Maven Central.

Remove outdated info including yet another Maven 2 reference

---

content/apt/pom.apt.vm

Fix versions comparison https://issues.apache.org/jira/browse/MNG-7559
intention is:
* 1.0.0.RC1 < 1.0.0-RC2
* ( edr, pfd, etc.) < final, ga, release
* 9.4.1.jre16 > 9.4.1.jre16-preview
following semver rules should be encouraged, natural ordering is used without the need to hard code strings, except for hard coded qualifiers 'a', 'b', 'm', 'cr', 'snapshot', 'final', 'ga', 'release', '' and 'sp':
* alpha = a < beta = b < milestone = m < rc = cr < 'snapshot' < '' = 'final' = 'ga' = 'release' < 'sp'
the documentation should discourage the usage of 'CR', 'final', 'ga', 'release' and 'SP' qualifiers.
Maven Central should begin to reject new artifact using CR and SP qualifiers.

[MNG-7559] Improve documentation of versions comparison

---

content/apt/guides/mini/guide-maven-classloading.apt
content/apt/guides/mini/guide-using-extensions.apt
pom.xml
src/plantuml/buildExtensionClassRealm.puml
src/plantuml/pluginClassRealm.puml

Clarify differences between Core and Build extensions

[MNG-5771] Document all classloaders used in Maven

---

content/apt/guides/introduction/introduction-to-profiles.apt

Fix typo on line 55. It was "runnning" (with 3 n) but it should be "running"

Fix typo in introduction-to-profiles.apt

---

content/apt/guides/development/guide-maven-development.apt
content/apt/guides/mini/guide-http-settings.apt

As HTTP settings are not "wagon-only" anymore.

Add generic documentation how to configure transports

---

Jenkinsfile

Old workspace can contain corrupted git data
or contain data created by another git version

Clean workspace before build

---

content/apt/pom.apt.vm

According to recommendation a few lines below

Using an SPDX identifier as the license name in example

---

content/markdown/repository-management.md

* the old URL leads nowhere
I am not 100% sure about the new URL  - the `download` in there is perhaps not the best. That being said, I did not find anything better. I believe it is still much better than the current dead link.

Fix URL pointing to Sonatype Nexus OSS repository manager

---

content/xdoc/download.xml.vm

* forgotten in the previous commit 6a5780e8aa5c5ba7d76f98dd4d885e6a1bb74916
@elharo thanks for merging my previous PR so quickly!
This is a trivial fixup where I forgot to change one of the words in the Maven 4.x case.

Trivial wording fix in download page

---

pom.xml

* new pom.xml formatting rules are coming in from the parent POM. 'mvn verify' fails without these

Reformat pom.xml using 'spotless:apply'

---

content/markdown/settings.md

This fixes markdown formatting on page so that table of content linking works again.
Edit done through GitHub editor.
P.S. Markdown code blocks should end with ` ``` `. If a block ends with ` ```xml ` the parser assumes that a new code block should start.

Fix code blocks that wrap until bottom of page.

---

content/apt/plugin-developers/plugin-testing.apt

* addCliOption() and resetStreams() are deprecated in the current verifier version (2.0.0-M1)

Plugin testing: remove verifier example and instead link to verifier Getting Started guide

---

content/markdown/guides/introduction/introduction-to-the-pom.md

Not doing this is very bad practice that makes pom.xml files extremely inconvenient to process with standard XML tools such as DOM or XSLT.

Include namespace in project element

---

content/apt/guides/mini/guide-http-settings.apt
content/markdown/docs/3.9.0/release-notes.md
content/markdown/guides/mini/guide-resolver-transport.md
content/site.xml

And existing page rename to "advanced Wagon configuration" as that's what it is.

Add new resolver transport dedicated page

---

content/apt/guides/mini/guide-http-settings.apt
content/markdown/guides/mini/guide-resolver-transport.md

As some changes creeped in that are actually 3.9+ ONLY. Also, explain what is and what is not picked up from legacy configs.
This PR moves content added in commit 2647fb00efea98d0f9b21c2632e373bdf45742ad from Wagon page to Resolver Transport page.
---
https://issues.apache.org/jira/browse/MNG-7739

[MNG-7739] Clear up documentation

---

content/markdown/docs/history.md.vm
pom.xml

Signed-off-by: Olivier Lamy <olamy@apache.org>

document core is EOL before 3.8.8 (e.g we will not provide core release for bugs nor security issues).

---

content/markdown/docs/history.md.vm

The typo is probably due to a copy/paste mistake 😄

Fix release of date of Maven 3.9.2

---

content/apt/guides/mini/guide-configuring-maven.apt
content/apt/guides/mini/guide-using-toolchains.apt

I keep finding these things in random places

[MNGSITE-393] Remove still more Maven 2 references

---

content/markdown/configure.md
content/markdown/docs/3.3.1/release-notes.md
content/markdown/docs/3.3.9/release-notes.md
content/markdown/reference/maven-classloading.md

There is no such property in code .... only similar I can find in `mvn` script
```
exec "$JAVACMD" \
....
"-Dmaven.multiModuleProjectDirectory=${MAVEN_PROJECTBASEDIR}" \
${CLASSWORLDS_LAUNCHER} ${MAVEN_ARGS} "$@"
```
In documentation it is only used in context of `.mvn` directory,
so to not make users confused better will be remove it at all and replace by description that `.mvn` is placed in project's top level directory

Remove maven.projectBasedir properties from configuration

---

content/apt/guides/getting-started/index.apt
content/apt/guides/mini/guide-attached-tests.apt
content/apt/guides/mini/guide-site.apt
content/apt/guides/mini/guide-snippet-macro.apt
content/apt/plugin-developers/common-bugs.apt
content/apt/plugin-developers/cookbook/plexus-plugin-upgrade.apt
content/apt/pom.apt.vm
content/markdown/faq-unoffical.md

We should consequently use one property name
changed pages by replace in IDE:
https://maven.apache.org/guides/getting-started/index.html
https://maven.apache.org/guides/mini/guide-attached-tests.html
https://maven.apache.org/guides/mini/guide-site.html
https://maven.apache.org/guides/mini/guide-snippet-macro.html
https://maven.apache.org/plugin-developers/common-bugs.html
https://maven.apache.org/plugin-developers/cookbook/plexus-plugin-upgrade.html
https://maven.apache.org/pom.html
https://maven.apache.org/faq-unoffical.html - not linked anywhere, content is broken, I don't fix it 😄

Rename basedir to project.basedir

---

content/markdown/docs/history.md.vm

This fixes some simple glitches. However, I'm not sure the language accurately describes what's happening here. According to this page the last release in the 3.8.x branch is 3.9.6.

Minor grammar edits

---

content/apt/pom.apt.vm

The spec page had some edge case issues that were actually spec errors (as implementations were rightfully not doing this same).
Note: generic version in resolver is authoritative in Maven4 as maven-artifact versions are to be killed off.
---
https://issues.apache.org/jira/browse/MRESOLVER-334

[MRESOLVER-334] Align spec with implementation

---

content/apt/guides/mini/guide-using-toolchains.apt

Focus the description on how this is used by the developer rather than by Maven.  Also, Java 5 is a little old, and sun is defunct. @hboutemy

Edit and update

---

content/markdown/repositories/metadata.md

Update 'versionining' to 'versioning' in the metadata documentation. Confirmed that this matches the .xsd schema.

Fix typos in metadata documentation

---

content/apt/pom.apt.vm

https://issues.apache.org/jira/browse/MNG-338 (Maven 2.0-alpha-2) = "provide some hand holding for dependencies on non-distributable jars"

improve MNG-338 documentation on downloadUrl

---

content/apt/guides/getting-started/maven-in-five-minutes.apt

Since Maven 3.9.6 does not support 1.7 compiler, the sample project cannot be built as is. 
This is frustrating for an inexperienced user. 
The proposed fix was tested on Java 21.0.3, Win7 sp1+. 
P.S. Notice, the problem is not only with the docs.  The code issue is known but still unresolved:
https://issues.apache.org/jira/projects/MARCHETYPES/issues/MARCHETYPES-82?filter=allopenissues 
Even though the updated version was pushed to Maven Central Repository years ago: https://github.com/ywchang/maven-archetype-quickstart https://central.sonatype.com/artifact/com.github.ywchang/maven-archetype-quickstart 
In a meantime, the new user gets a build failure trying Maven for their first time.

Set both maven.compiler.source and maven.compiler.target to 1.8 

---

src/plantuml/buildExtensionClassRealm.puml
src/plantuml/pluginClassRealm.puml

This patch corrects the syntax used to put the license string.
Tested using https://www.planttext.com/ and http://www.plantuml.com/plantuml/uml/

Fix multiline comment syntax

---

content/markdown/settings.md

[MNGSITE-393] Assume 3.0 or later

---

content/apt/pom.apt.vm

- Similar to #543
Currently https://maven.apache.org/pom.html:
With this change I'm getting locally:

Escape properties to prevent evaluation

---

content/apt/examples/maven-3-lifecycle-extensions.apt.vm

Looks like these were older style javadoc links, which now show the non-frame root page.
Updating the links so they point directly to the correct extension classes

Correct the Javadoc links in maven-3-lifecycle-extensions

---

content/apt/pom.apt.vm

hello, i've found the main documentation site of Maven has a bad anchor reference, the page is `https://maven.apache.org/pom.html`, and the bad anchor is `https://maven.apache.org/pom.html#The_Build_Element_Set`.
this is the page:
The later one can't jump to its target section, i tried to fix it.

update POM Reference page's TOC bad anchor

---

content/site.xml
content/xdoc/errors/404.xml.vm
pom.xml

Both need to be updated in tandem to get proper rendering results.
Addresses one of the issues from https://the-asf.slack.com/archives/C7Q9JB404/p1715479275966359

Bump Maven Site Plugin AND Maven Fluido Skin

---

content/markdown/guides/mini/guide-resolver-transport.md

Maven 3.9 still uses Resolver 1.x, so the documentation should refer to the proper version instead of version 2.x (which is quite different).
To be reverted once 4.0 is out.

[MNG-8231] Link to latest resolver-1.x documentation instead of current

---

content/apt/pom.apt.vm

Link is currently broken, it links to #plugins but should be Plugins. See https://maven.apache.org/pom.html#:~:text=with%20the%20attributes%20combine.children%20or%20combine.self%20outlined%20in

Fix link to Plugins section

---

content/apt/guides/introduction/introduction-to-dependency-mechanism.apt

The broken link in the TOC of the page was fixed by replacing the manual written TOC, by the command to generate it.

MNGSITE-547 Fix broken TOC on dependency mechanism guide

---

content/apt/developers/conventions/code.apt
content/apt/developers/conventions/git.apt
content/apt/developers/release/maven-project-release-procedure.apt
content/apt/guides/development/guide-maven-development.apt
content/apt/guides/index.apt.vm
content/apt/guides/mini/guide-maven-classloading.apt
content/apt/guides/plugin/guide-java-plugin-development.apt.vm
content/apt/plugin-developers/common-bugs.apt
content/apt/pom.apt.vm

Several pages were rendered with broken TOCs or where headings were rendered as links.
This PR fixes (hopefully) all of them.

Align TOCs and render headings no longer as links

---

content/apt/guides/index.apt.vm

On the guides/index.html site, the link to the "introduction to repositories" page is broken.

Fix link to "Introduction to repositories" page on guides-index

---

.asf.yaml
.github/ISSUE_TEMPLATE/BUG.yml
.github/ISSUE_TEMPLATE/IMPROVEMENT.yml
.github/ISSUE_TEMPLATE/config.yml
README.md
pom.xml

I hope that we not need an issues migration for this project - it is simply current state of site.
We have 66 issues opened now:
https://issues.apache.org/jira/projects/MNGSITE
After it we can create a pined issue with information and link to JIRA
Next steps after merge:
- block for creating new issues in JIRA - existing issues should be possible to comments, closing and so on

Enable GitHub issues

---

content/apt/guides/introduction/introduction-to-dependency-mechanism.apt

Was the only reference I found.
If this URL is opened it redirects to current version (RC2 as of today).

[MNGSITE-526] Fix URL of 4.1.0 XSD

---

content/apt/plugin-developers/common-bugs.apt

Most plugins now converted to use constructor injection with Guice so this should not be a problem.
Might want to wait for some releases before we merge this.

Now using constructor Injection with Guice

---

content/markdown/scm.md

The URL in the repo init snippet is resolved to the GitHub repository, so the GitHub URL can be used directly.

Housekeeping SCM Page

---

content/markdown/tools/index.md
content/site.xml

This PR adds a new section "Maven Tools" to the site's navigation to create a place about tools aside Maven itself, similar to the plugin page. Initially only the Maven Daemon is listed on the index page, but in the future more tools can be added, e.g. Maven Shell, Maven Encrypt etc.

MNGSITE-534 Mention Maven Daemon

---

content/markdown/developers/conventions/github.md

Use the same as we have in JIRA.
Continuation of: https://github.com/apache/maven-gh-actions-shared/pull/129

Update list of GitHub priority labels

---

content/apt/guides/plugin/guide-java-plugin-development.apt.vm

1. Typos
2. Subject verb agreement
3. Java 5 features like `@Override`
4. Match Java terminology to Oracle's usage
5. Tighten up by omitting needless words, switching to active voice, etc.

Edit  guide to java-plugin development for clarity

---

content/apt/guides/mini/guide-releasing.apt

According to docs of the plugin itself as well of my understanding of the plugin code myself, the clean phase is executed by default after a successful release by default (DefaultReleaseManager).
So I updated this in the docs on site.
Closes #MNGSITE-446.

[MNGSITE-446] Properties file gets deleted by default.

---

content/apt/guides/mini/guide-multiple-modules.apt
content/markdown/glossary.md
content/markdown/guides/mini/guide-multiple-subprojects-4.md

This uses the definition created in the What's new in Maven 4 article.

[MNGSITE-541] Define project and subproject

---

content/markdown/repositories/artifacts.md

I think we still need to more precisely define "dependency type" but this is a good start.

[MNGSITE-521] Copy edit and clarify artifacts.md

---

content/apt/developers/index.apt

The developers index page (https://maven.apache.org/developers/index.html) does not contain the GitHub convention link the main menu has. This PR aligns both.

Add a link to Github convetions on the developers index page

---

content/markdown/project-roles.md

Fix link and add "PMC only" label on project-roles page

---

content/markdown/docs/history.md.vm

Based on the slack discussion, I added a small information what does EOL means for Maven and that there is no difference between EOL and EOS for us.

Add info about EOL to release history.

---

content/apt/pom.apt.vm

No longer uses the ambiguous term "lexicographic". More clearly distinguish the comparison of version strings and the individual tokens parsed from the string. 
This is not intended to change anything, simply to more carefully document the existing behavior.

[MNGSITE-441] More carefully define version string and token ordering

---

content/markdown/whatsnewinmaven4.md
content/site.xml

This PR adds an article about the major changes in Maven 4.

[MNGSITE-550] What's new in Maven 4?

---

content/markdown/repositories/artifacts.md

I found this page https://maven.apache.org/repositories/artifacts.html very confusing and hard to follow, so I rewrote it to more clearly distinguish between element values and internal properties. I tried to tighten up the language and indicate that type handlers also affect classifiers.

Clarify types, extensions, and classifiers

---

content/apt/pom.apt.vm

Fix version order specification

---

content/apt/guides/introduction/introduction-to-the-lifecycle.apt
content/apt/guides/mini/guide-configuring-plugins.apt
content/apt/pom.apt.vm

This PR updates the articles about plugin configuration and lifecycle to 
- make clear that Maven 4 breaks build when plugin is defined multiple times [MNGSITE-519]
- describe execution merge and inheritance more clear [MNGSITE-362]
- add Maven 4 execution priorities
- fix some formatting errors in the affected pages
The additions are all in this PR as they affect the same section of the configuration page.
Merge and inheritance behavior were verified with Maven 4.0.0-rc3 while updating the docs.

Update articles about plugin execution configuration

---

content/xdoc/download.xml.vm

Follow up of #719 brought up in Slack
Download is actually:
`https://downloads.apache.org/maven/mvnd/1.0.2/maven-mvnd-1.0.2-src.zip` etc. so `src` instead of `source-release`

Fix downloadlink for Daemon

---

content/site.xml

Minor change: It should say Downloads instead of Download in site navigation. 
There is more than one thing to download: different files for the latest Apache Maven version, Apache Maven Daemon (mvnd) and other previous stable releases.

Downloads instead of Download

---

content/markdown/docs/3.9.9/release-notes.md

There is a typo, the correct version is 1.9.22

Fix Resolver upgrade version in 3.9.9 release-notes.md

---

content/apt/users/index.apt
content/markdown/guides/mini/guide-migration-to-mvn4.md
content/site.xml
content/xdoc/index.xml.vm

Wrote a guide for user how to migrate projects to Maven 4.
Goal is to provide a guideline, which gets continuously updated in the future, when people share their experiences and issues.
As it's a user guide it was placed in the user section. Also the "What's new in Maven 4" article, which also aims at users as an audience, was moved there (in terms of navigation). To give both some visibility, when people open the Maven site, links were added to the landing page.

User guide: Migrate projects to Maven 4

---

content/apt/developers/conventions/code.apt

MNGSITE-500 turned a bit from add a note about spotless to another "does anyone provide a formatter?", which is not part of site, but of shared-resources (where issues exists). As it's unclear when formatters for Eclipse and other IDE are provided in shared-resources, this PR adds a note about the IDE plugin offered by palantir itself (which are up to date, for example IntelliJ plugin was updated some days ago).

[MNGSITE-500] Notice IDE plugins for palantir on code convention page

---

content/site.xml

Based on the proposal in #726 

Update navigation for User Centres

---

content/apt/plugins/index.apt
content/filtered-resources/.htaccess
content/markdown/developers/website/component-reference-documentation-helper.md
content/resources/components.links
content/resources/tools/components.links

with the creation of https://maven.apache.org/tools/ directory as part of #811 
it becomes natural to move Maven Wrapper from https://maven.apache.org/wrapper/ to https://maven.apache.org/tools/wrapper/
this PR does some aspects of smooth transition:
- create symlinks for https://maven.apache.org/tools/wrapper/ and https://maven.apache.org/tools-archives/
- do url redirects
- prepare [Component Release Documentation Helper](https://maven.apache.org/developers/website/component-reference-documentation-helper.html) for future releases 
just before merging this PR, content in svn website HTML will have to be prepared:
```
svnmucc -m "move /wrapper to /tools/wrapper (maven-site#838)" \
-U https://svn.apache.org/repos/asf/maven/website/components \
mv wrapper-archives tools-archives \
mkdir …
```

move /wrapper to /tools/wrapper with /tools-archives

---

content/resources/xsd/.htaccess

Removing redirect for `toolchains-1.1.0.xsd`, which has been released and is present in `content/resources/xsd`, but where a redirect to a non-existent rc-3 file is causing a 404.
you have to …

Update .htaccess to fix bad toolchains-1.1.0.xsd redirect

---

content/site.xml

Having _Run_ and _Use_ in the navigation is confusing.
Most people, me included, expect the contents of the menu item _Run_ to show up when clicking  _Use_.
I don't think the menu item _Use_ adds much on itself in the About Maven section, therefore I would suggest removing it.

Dropped Use and renamed Run to Use in the About Maven section

---

README.md

Also refresh badges links
Look like we don't remember to check it 😄 
will look as:

Add badge for dist-tools errors
