content/apt/guides/introduction/introduction-to-dependency-mechanism.apt
This one's optional. There was nothing incorrect in the original, but I thought we might be clearer, more active, and somewhat more specific about the benefits of Maven.
=> Rewrite intro paragraph

content/apt/plugins/index.apt
=> Google code is defunct

content/apt/examples/maven-3-lifecycle-extensions.apt.vm
=> metadata is plural

content/markdown/background/history-of-maven.md, content/markdown/ide.md, content/markdown/maven-ci-friendly.md, content/markdown/maven-conventions.md, content/markdown/maven-jsr330.md, content/markdown/project-roles.md, content/markdown/reference/maven-classloading.md, content/markdown/run.md, content/markdown/security-plexus-archiver.md
All IDEs and text editors have a spell checking feature (or plug-ins). 😇
I have used this one to detect and fix typos in the 'content/markdown' folder:
https://github.com/bartosz-antosik/vscode-spellright
=> Fix various typos using a spell checker ✅

content/apt/guides/introduction/introduction-to-dependency-mechanism.apt
=> spelling and slight reordering of adverbs

content/xdoc/download.xml.vm
=> subject verb agreement

content/apt/guides/mini/guide-naming-conventions.apt
=> Reversed domain name group IDs are a convention

content/apt/guides/plugin/guide-java-plugin-development.apt
=> fixed point is not the same as integer

content/markdown/what-is-maven.md
=> small tightening of language and grammar

content/apt/repository/guide-central-repository-upload.apt
=> Grammar fixes

content/apt/pom.apt
=> Whereas is one word

content/apt/guides/getting-started/maven-in-five-minutes.apt
Added "Java 9 or later" section to the "Maven in 5 Minutes" page.
=> Added "Java 9 or later" section to "Maven in 5 Minutes"

content/apt/guides/mini/guide-default-execution-ids.apt
Correcting a tiny typo I noticed on my travels through the Maven docs.
=> Small spelling correction

content/apt/guides/mini/guide-configuring-plugins.apt
We should not use the doclets anymore and also they were not working when I tried, 
we can use @Parameter instead.
=> Moving parameters doclets to annotation

content/markdown/what-is-maven.md
=> Improves what-is-maven.md

content/apt/guides/mini/guide-configuring-plugins.apt
Remove typo from guide-configuring-plugins.apt
=> Improve guide-configuring-plugins.apt

content/apt/guides/introduction/introduction-to-optional-and-excludes-dependencies.apt
=> fix typo in introduction-to-optional-and-excludes-dependencies.apt

content/apt/guides/introduction/introduction-to-dependency-mechanism.apt
=>  missing comma and grammar nit

content/apt/skins/index.apt, pom.xml
- by default anonymize client IP for Google Analytics
=> Upgrade Fluido Skin from 1.7 to 1.8

content/apt/pom.apt
=> Don't worry about things that haven't been true since 2.0

content/apt/guides/mini/guide-configuring-plugins.apt
=> Clarify language

content/apt/pom.apt
=> grammar fix

content/apt/developers/conventions/code.apt
=> Clean up and clarify

content/apt/guides/development/guide-maven-development.apt
=> SVN page is 404

content/apt/developers/index.apt
=> Others --> Other

content/apt/pom.apt
@michael-o Quick typo I noticed while studying the larger bug here
=> hypen -> hyphen

content/apt/pom.apt
@rfscholte @hboutemy This seems like a straightforward description that covers most common use cases. Unfortunately I'm not sure it's true, especially when plus signs (build identifiers) are considered. Posting for discussion.
=> [MNGSITE-387] Mention semantic versioning

content/apt/pom.apt
@michael-o I keep forgetting this isn't markdown. :-(
=> Fix link syntax

content/apt/pom.apt
=> Update Java versions for 2019

content/apt/developers/conventions/jira.apt
@hboutemy Mostly I cleaned this up and removed some sections that no longer seem to be followed. I'd like to expand this further, but those changes will need to be discussed on the mailing list first.
=> Update for grammar and to reflect current practice

content/apt/guides/mini/guide-configuring-plugins.apt
=> Clarify and omit needless words

content/apt/guides/introduction/introduction-to-profiles.apt
@hboutemy as currently written, one might think profiles are not a Maven 3 feature
=> Don't reference Maven 2.0 specifically

content/markdown/settings.md
=> misleading typo

content/apt/guides/mini/guide-coping-with-sun-jars.apt
@hboutemy There's probably more we need to update on this page including s/Sun/Oracle/
=> java.net is dead

content/apt/guides/mini/guide-configuring-plugins.apt
=> slight rewrite to improve flow

content/apt/developers/conventions/code.apt
=> update IDE instructions

content/apt/guides/introduction/introduction-to-plugins.apt, content/apt/guides/introduction/introduction-to-the-lifecycle.apt, content/apt/guides/mini/guide-building-for-different-environments.apt, content/apt/guides/mini/guide-default-execution-ids.apt, content/markdown/faq-unoffical.md, content/markdown/maven-2.x-eol.md, content/markdown/maven-logging.md, content/markdown/settings.md, content/pdf.xml, content/resources/xsd/maven-4.0.0.xsd, content/resources/xsd/maven-v3_0_0.xsd
@michael-o There are more to go, but this is a start.
=> [MNGSITE-393] remove many references to Maven 1.x and 2.x

content/xdoc/articles.xml
=> docs: java blackbelt is defunct

content/apt/pom.apt
There are several typos to be fixed and improvement opportunities to be done.
=> MNGSITE-400 Introduce several fixes into the `POM Reference` document

content/apt/developers/release/maven-project-release-procedure.apt
=> Update link to apache instructions

content/markdown/what-is-maven.md
=> [MNGSITE-397] Rewrite and clarify

content/pdf.xml
=> [MNGSITE-393] retitle without Maven 2

content/apt/developers/release/maven-project-release-procedure.apt
=> correct URL for instructions

content/apt/guides/mini/guide-maven-classloading.apt
=> [MNGSITE-393] remove reference to Maven 2

content/apt/plugin-developers/common-bugs.apt
=> [MNGSITE-393] remove old section on plexus-utils

content/apt/guides/development/guide-documentation-style.apt
=> docs: remove broken link and fix typos

content/apt/plugin-developers/plugin-testing.apt
=> docs: minor grammar issues

content/xdoc/articles.xml
=> [MNGSITE-393] remove some outdated books and 404 links

content/xdoc/articles.xml
=> [MNGSITE-393] remove still more very outdated content

content/apt/developers/index.apt
=> [MNGSITE-407] Link to our own Jenkins build

content/markdown/maven-jsr330.md
=> [MNGSITE-393] we do not support Maven 2

content/apt/guides/development/guide-helping.apt
=> docs: remove links that don't go where they say

content/xdoc/index.xml.vm
Submitted by: David Pead
o change events <img> to float left
=> [MNGSITE-408] Fix alignment of events logo

content/markdown/docs/history.md.vm
=> [MNGSITE-415] say Maven 3.0.x is EOL

content/apt/guides/introduction/introduction-to-dependency-mechanism.apt
=> docs: clarify dependency scope rules

content/apt/developers/dependency-policies.apt
=> docs: subversion URLs no longer exist

content/apt/guides/introduction/introduction-to-dependency-mechanism.apt
modified:   content/apt/guides/introduction/introduction-to-dependency-mechanism.apt
- TOC:    * {{{bill-of-materials-bom-poms}Bill of Materials (BOM) poms}}
- ** {Bill of Materials (BOM) poms}
=> Introduce section heading for BOM pattern

content/apt/developers/release/maven-project-release-procedure.apt
=> docs: listing a release requires PMC membership

content/apt/repository/guide-central-repository-upload.apt
@rfscholte 
also passive voice to active voice
=> docs: must --> should

content/markdown/community.md
=> docs: grammar

content/apt/guides/introduction/introduction-to-dependency-mechanism.apt
=> minor grammar nits

content/xdoc/articles.xml
Add a reference to the blog post 'Introduction to Maven Toolchains' by myself.
=> Add 'Introduction to Maven Toolchains' blog

content/apt/guides/introduction/introduction-to-the-pom.apt
=> Docs: Material change in pom, "or" is a "non-exclusive"

content/apt/guides/getting-started/maven-in-five-minutes.apt
@michael-o omit needless words
=> docs: minor cleanup

content/apt/pom.apt
=> docs: remove forward looking statement

content/apt/pom.apt
@michael-o focus on element's expected content, and in general be a little less flip and somewhat more direct
=> docs: rewrite More Project Information

content/apt/guides/mini/guide-3rd-party-jars-local.apt
Fixed some unusual phrasing I saw while reading the docs. 
Goal is to leave things even better than I found them.
=> Minor improvement to English fluency

content/markdown/extensions/index.md
=> Update extensions index.md

content/apt/developers/compatibility-plan.apt, content/apt/developers/index.apt, content/apt/developers/release/maven-project-release-procedure.apt, content/apt/developers/retirement-plan-plugins.apt, content/apt/developers/website/deploy-component-reference-documentation.apt, content/apt/developers/website/index.apt, content/xdoc/scm.xml
I hope that all ci-build was replaced
=> [MNGSITE-462] Update Maven jenkins address

content/apt/guides/mini/guide-repository-ssl.apt
@michael-o This functionality should be available in 3.x
=> [MNGSITE-393] remove another Maven 2.x mention

content/markdown/extensions/index.md
Update "[Maven/ Available Extensions](https://maven.apache.org/extensions/index.html)", add the [OpenTelemetry Maven Extension](https://github.com/open-telemetry/opentelemetry-java-contrib/tree/main/maven-extension.)
=> Update "Maven/ Available Extensions", add OpenTelemetry Maven Extension

content/apt/developers/conventions/code.apt, content/resources/developers/maven-idea-codestyle.xml
It is the most used layout in Maven core project.
=> [MNGSITE-465] Java Code Convention - import layouts

content/markdown/repository-management.md
Added a link to Bytesafe which has support for Maven
=> Added Bytesafe to Available Repository Managers

content/resources/developers/maven-idea-codestyle.xml
Based on Java style - Useful eg for preparing scripts for maven-invoker-plugin
=> IntelliJ IDEA - code style for Groovy

content/apt/developers/committer-environment.apt, content/apt/developers/conventions/code.apt, content/resources/developers/maven-eclipse.importorder
Related to MNGSITE-465; the configuration matches the screenshot seen in https://github.com/apache/maven-site/pull/269#issuecomment-945622992 .
=> Add import order configuration for Eclipse

content/apt/guides/mini/guide-configuring-plugins.apt
=> Docs: clean up language

content/apt/guides/getting-started/index.apt
=> Fix docs typo

content/apt/examples/maven-3-lifecycle-extensions.apt.vm, content/apt/guides/mini/guide-using-extensions.apt
=> [MNGSITE-496] Outline all means to load extensions and clarify

content/apt/pom.apt.vm
=> Remove yet another reference to Maven 2

content/apt/guides/mini/guide-attached-tests.apt
=> Simplify page

content/filtered-resources/.well-known/security.txt, pom.xml
https://issues.apache.org/jira/browse/MNGSITE-503
References:
* [.well-known/security.txt at maven.apache.org (mail-archive.com)](https://www.mail-archive.com/dev@maven.apache.org/msg128366.html)
* [.well-known/security.txt at maven.apache.org-Apache Mail Archives](https://lists.apache.org/thread/tvfg1lx9nd72c9t4t4s3zlx6l0tpnmwy)
=> [MNGSITE-503] add .well-known/security.txt

content/markdown/docs/3.8.7/release-notes.md, content/markdown/docs/history.md.vm, pom.xml
=> Add release notes for Maven 3.8.7

content/apt/guides/mini/guide-configuring-plugins.apt
=> Fix formatting to have XML rendered correctly

content/xdoc/download.xml.vm
* 'Maven' is used as singular in this case, so I _believe_ the rest of the sentence should follow that
* NOTE: I am not a native English speaker so I may have missed something which makes the original wording valid
=> Minor wording fix in download page

content/apt/guides/mini/guide-attached-tests.apt
=> fix markup

content/apt/skins/index.apt
Added new Site skin information to documentation
=> MSITE-909 - Added new Site skin information to documentation

content/markdown/docs/3.9.0/release-notes.md, content/markdown/docs/history.md.vm, pom.xml
Some links (announce) are still just copy-pasta...
=> Prepare release notes for Maven 3.9.0

content/apt/guides/introduction/introduction-to-profiles.apt, content/apt/pom.apt.vm
Improve structure within profile activation documentation
=> [MNGSITE-502] Document profile activation based on packaging

content/markdown/docs/3.9.0/release-notes.md
Provide high level changes and improvements with some links.
=> Extend release notes for 3.9.0

content/markdown/guides/plugin/guide-java-plugin-development.md
- fix anchors in links
- fix example of using setter for plugin parameters
- a little reformat
=> Refresh - Guide to Developing Java Plugins

content/apt/guides/mini/guide-proxies.apt
They MAY work but that is NOT the official way of doing things nor should be considered as proper way: it is implementation detail of transport (does it obey or not).
=> Clarify the use of Java system properties

pom.xml
somebody must have updated without running `mvn test`
=> spotless fix

content/apt/guides/mini/guide-reproducible-builds.apt
The [reproducible build wiki](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=74682318#Reproducible/VerifiableBuilds-Whataretheissuestosolve?) has the correct information. this just updates the main site.
=> Harmonise Spring Boot plugin information

content/markdown/docs/3.9.3/release-notes.md, content/markdown/docs/history.md.vm, pom.xml
Site changes for Maven 3.9.3 release
=> Maven 3.9.3 Release notes

content/markdown/repository-management.md
I have not checked the other links.
=> Fix broken link to Gitea's repository manager support

content/apt/guides/introduction/introduction-to-profiles.apt
=> [MNGSITE-372] Clarify how multiple profile activation types are combined

content/apt/guides/introduction/introduction-to-profiles.apt
=> [MNGSITE-393] Remove Maven 2 references

content/markdown/docs/3.9.0/release-notes.md, content/markdown/docs/3.9.1/release-notes.md, content/markdown/docs/3.9.2/release-notes.md, content/markdown/docs/3.9.3/release-notes.md, content/markdown/docs/3.9.4/release-notes.md
---
https://issues.apache.org/jira/projects/MNG/issues/MNG-7887
=> [MNG-7887] Update release notes with new breakage

content/apt/developers/release/maven-project-release-procedure.apt
- link to doc of GPG key preparation
- more detail about preparing release notes
=> Improvements to release procedure

content/apt/pom.apt.vm
Fix some links, add reference to special plugin configuration inheritance attributes
=> [MNG-6059] clarify URL inheritance

content/apt/developers/compatibility-plan.apt, content/markdown/docs/history.md.vm
References:
https://github.com/apache/maven-site/commit/e1a353dfd98f0cc716fa3ad45409ed109072f9b0 #398 
https://github.com/apache/maven-site/commit/5cb62af4d232ee06c1fe2239b81cd06fc4b02501 #410 
https://github.com/apache/maven-site/commit/9f3a79c441837dd01e2b00cddf578ac54d492a8f 
https://lists.apache.org/thread/k2g3cy4hfktg159ckx0vk9hygrotnj11
=> Maven 3.6.3 as minimum requirements for plugins

content/apt/pom.apt.vm
Clean up example snippet for repositories
=> Clarify default values for repositories

content/markdown/repository-management.md
=> Remove defunct and archived repo managers

content/apt/developers/compatibility-plan.apt
=> [MNG-8061] Maven >4.0.0-alpha-12 requires Java 17

content/apt/guides/introduction/introduction-to-profiles.apt, content/apt/pom.apt.vm
Extend description in POM reference.
=> [MNG-5726] Describe regex matching for OS version profile activation

content/apt/developers/release/parent-pom-release.apt
References:
- https://github.com/apache/maven-apache-parent/pull/206
- https://github.com/apache/maven-parent/pull/169
=> [MPOM-478] Simplify release of parent POMs

content/apt/developers/release/parent-pom-release.apt
https://github.com/apache/maven-apache-parent/pull/210
https://github.com/apache/maven-parent/pull/171
=> [MPOM-483] Update Releasing A Parent POM according to new modules

content/apt/guides/introduction/introduction-to-archetypes.apt
It seems that something is missing in the first sentence of this paragraph.
There are multiple options, but just adding "work" seems to be fine.
Thinking out loud, it could also be:
"Using archetypes provides a great way to enable developers create projects quickly in a way consistent with best practices employed by your project or organization."
=> Fix a typo.

content/markdown/guides/plugins/validation/index.md
- https://issues.apache.org/jira/browse/MNG-7939
=> Add documentation for maven.plugin.validation.excludes

content/xdoc/download.xml.vm
Unsure where else?
---
https://issues.apache.org/jira/browse/MNG-8070
=> [MNG-8070] Document requirement for Java 17

content/markdown/code-quality-management.md, content/markdown/community.md, content/markdown/developers/conventions/jira.md, content/markdown/developers/release/maven-core-release.md, content/markdown/docs/history.md.vm, content/markdown/extensions/index.md, content/markdown/glossary.md, content/markdown/guides/mini/guide-multiple-modules-4.md, content/markdown/guides/mini/guide-resolver-transport.md, content/markdown/issue-management.md, content/markdown/maven-1.x-eol.md, content/markdown/maven-conventions.md, content/markdown/maven-logging.md, content/markdown/privacy-policy.md, content/markdown/release-notes-all.md.vm, content/markdown/repository-management.md, content/markdown/repository/layout.md, content/markdown/security.md, content/markdown/settings.md, content/markdown/what-is-maven.md
Factored out from the other PR.
=> Fix section indents

content/markdown/docs/3.9.7/release-notes.md, content/markdown/docs/history.md.vm, pom.xml
Draft of Maven 3.9.7 release notes.
=> Maven 3.9.7 release notes

content/apt/guides/introduction/introduction-to-the-pom.apt
In the introduction to the pom.xml
=> Always link to the latest released super pom

content/markdown/docs/3.9.8/release-notes.md, content/markdown/docs/history.md.vm, pom.xml
The draft for Maven 3.9.8 release notes.
=> Maven 3.9.8 release notes

content/markdown/docs/3.9.9/release-notes.md, content/markdown/docs/history.md.vm, pom.xml
Release notes and site update for Maven 3.9.9
=> Maven 3.9.9 Release Notes

content/apt/guides/plugin/guide-java-plugin-development.apt.vm
The `plugin` tag need in `plugins` tag.
=> fix: fix plugin define xml

content/markdown/project-roles.md
This is not what we're usually doing and not what we should be doing.
I avoided making more affirmat\ive statements about what we should be doing. I'm not sure this is the right page for that, but I'll look through the site and see if we say anything anywhere else.
=> Remove "Commit then Review"

content/apt/guides/introduction/introduction-to-the-lifecycle.apt
and some other minor copy edits
=> [MNGSITE-393] Remove Maven 2.0 content

content/apt/guides/introduction/introduction-to-archetypes.apt
=> Remove hallucinated mojo archetype

content/xdoc/scm.xml
No need to reference siubversion
=> All our projects use git these days

content/markdown/settings.md
Do not merge until #525 is merged.
=> Use TOC macro instead of hardcoded TOC

pom.xml
Fixes source rendering e.g. on
[developers/release/maven-core-release.html](https://maven.apache.org/developers/release/maven-core-release.html)
Compare with https://issues.apache.org/jira/browse/MSKINS-258
=> Use Fluido 2.0.1

content/apt/guides/development/guide-testing-development-plugins.apt
JIRA issue: [MNGSITE-549](https://issues.apache.org/jira/projects/MNGSITE/issues/MNGSITE-549)
fixed automatically check example:
```xml
<pluginRepositories>
<pluginRepository>
<id>apache.snapshots</id>
<url>https://repository.apache.org/snapshots/</url>
<snapshots>
<enabled>true</enabled>
<updatePolicy>interval:15</updatePolicy>
</snapshots>
</pluginRepository>
</pluginRepositories>
```
=> [MNGSITE-549] - fixed automatically check example

content/markdown/docs/3.5.0-beta-1/release-notes.md, content/markdown/docs/3.5.0/release-notes.md, content/markdown/maven-ci-friendly.md, content/site.xml
This PR formats the files that will later be updated with the actual content  for MNGSITE-539, so the formatting is split.
=> #MNGSITE-539 Formatting the affected files

content/markdown/configure.md
=> Copy edits

content/apt/guides/development/guide-helping.apt, content/markdown/issue-management.md, content/markdown/support-and-training.md, content/xdoc/errors/404.xml.vm, content/xdoc/scm.xml
=> GitHub issues - update links for issues system

content/markdown/scm.md
During studying the SCM page, I found a typo and a wrong link reference
=> Housekeeping on SCM Site

content/apt/guides/mini/guide-configuring-maven.apt
=> [MNGSITE-393] Remove another mention of Maven 2

content/apt/pom.apt.vm
So there's no link phase.
and as always omit needless words.
=> Java doesn't statically link

pom.xml
This requirement has been introduced with the update of plantuml-maven-plugin to 0.3
=> Enforce Java17 or above for building

content/markdown/project-roles.md
Reverts apache/maven-site#569
as asked https://lists.apache.org/thread/gzocjd8qn3729z1koz62v25d4h5fz0mn
=> Revert "Remove "Commit then Review""

.github/workflows/verify-site.yml
=> Install graphviz - dot utility

content/apt/guides/introduction/introduction-to-dependency-mechanism.apt
Markdown snuck in but that doesn't work
=> Use apt syntax

content/site.xml
=> Update site descriptor to 2.0

content/apt/pom.apt.vm
=> Fix spelling typo

content/apt/developers/release/maven-project-release-procedure.apt
As we use Commit then Review policy,
this allows to easier show what was changed from latest release
=> Add link to all commits to Vote template

content/apt/guides/introduction/introduction-to-profiles.apt
I was looking for an example like this recently. And I was surprised that there's an example for profile activation with property value false but not example of profile activation with property value true.
=> Add example of profile activation with value true

content/apt/developers/release/maven-project-release-procedure.apt
=> Hint about release drafter during vote

content/markdown/maven-logging.md
* Updating to section "Changing the SLF4J implementation" section
* Fixing some mistakes and broken link
=> [MNGSITE-463] Update Maven Logging page

Jenkinsfile
To avoid use old site cache from previous builds
=> Use jenkins workspace as site cache

content/markdown/docs/history.md.vm
=> Add link to Maven 4.0.0-rc3 announcement

content/markdown/whatsnewinmaven4.md
Following this checklist to help us incorporate your contribution quickly and easily:
If your pull request is about ~20 lines of code you don't need to sign an [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure please ask on the developers list.
To make clear that you license your contribution under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) you have to acknowledge this by using the following check-box.
Before
After
=> Improve display of quote

content/apt/guides/introduction/introduction-to-the-pom.apt
It is easier for readers to be able to follow the hyperlink instead of having to locate the target document in the menu.
----
=> Include a hyperlink to existing document (POM reference) in the documentation

content/markdown/whatsnewinmaven4.md
Also small rephrasing to the recommendation to not use clean install for regular builds.
=> Add all and each phase to Maven 4 article

content/markdown/guides/mini/guide-migration-to-mvn4.md
=> Fix typos and grammar in maven 4 migration guide

src/plantuml/maven-sources/doxia.puml
=> Add missing Doxia modules to sources overview

src/plantuml/maven-sources/shared.puml
=> Fix module name/URL of "file-management"

src/plantuml/maven-sources/misc.puml
These modules were missing in the graphics.
Additionally the modules were ordered (slightly)
lexicographically to make alignment
with apache-sources/default.xml easier.
you have to acknowledge …
=> Add missing modules to Maven "misc" overview

content/markdown/issue-management.md
Can be merged after https://github.com/apache/maven-doxia/pull/267
Updating Doxia-Site is on the list
=> Update issue-management.md with correct GH issues links

content/apt/guides/development/guide-plugin-documentation.apt.vm, content/apt/guides/plugin/guide-java-plugin-development.apt.vm, content/apt/plugin-developers/index.apt, content/site.xml
Fixes #749
Any feedback is appreciated!
----
=> Mention Plugin Documentation Guide more prominently

content/markdown/guides/mini/guide-maven-ci-friendly.md
=> Update guide CI-friendly versions for Maven 4

content/apt/developers/release/maven-project-release-procedure.apt
=> Release procedure - adjust information about release notes and milestones

content/markdown/repositories/metadata.md
- [ x] Your pull request should address just one issue, without pulling in other changes.
- [ x] Each commit in the pull request should have a meaningful subject line and body.
- [ x] Run `mvn site` and examine output in `target/site` directory.
the [Apache License Version 2.0, January …
=> Updates repositories/metadata.md to fix a broken link

content/markdown/repository-management.md
* currently resolves to 404 error
* page has moved from
- https://docs.gitea.com/packages/usage/packages/maven to
- https://docs.gitea.com/usage/packages/maven
- [ X] Your pull request should address just one issue, without pulling in other changes.
- [X ] Each commit in the pull request should have a meaningful subject line and body.
- [ X] Run `mvn site` and examine output in `target/site` directory.
[Individual Contributor License …
=> repostory-management: fix gitea link

content/markdown/developers/compatibility-plan.md
=> Fix anchors on Maven Plugins Compatibility Plan

content/markdown/repository/guide-central-repository-upload.md
=> Replace OSSRH link by Central Portal

.asf.yaml
=> Cleanups protection for test branch

pom.xml
=> mvnd 1.0.3 released
